name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Contract tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Use Bun 1.1.16
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.16

      - run: bun install --frozen-lockfile

      - name: Run tests
        run: bun --filter contracts test
